_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": linux-x86_64
dataset:
    value: text8 + hacker_news
vocab_size:
    value: 1130
